const selectors = {

  common: {
    addButton: '.cta-block .btn-primary',
    cardViewButton: '.btn-secondary .fa-th',
    listViewButton: '.btn-secondary .fa-list',
    searchField: '.search-input-container .form-control',
    filterOptionSelect: '.custom-select',
    ascendingOrder: '.btn-light .fa-arrow-down',
    descendingOrder: '.btn-light .fa-arrow-up',
    publishedList: '.btn-light .fa-eye',
    unpublishedList: '.btn-light .fa-eye-slash',
    flyOutMenu: '.custom-icon-button .fa-ellipsis-v',
    pageTitle: 'h1.title',
    emptyStateContainer: '.empty-state-container',
    saveButton: '.modal-footer >button:nth-child(1)',
    saveButtonOfPage: '.btn.btn-primary',
    cancelButton: '.modal-footer >button:nth-child(2)',
    cancelButtonOfPage: '.btn.btn-light',
    modalCloseButton: '.modal-header .custom-icon-button',
    flyoutMenuCardviewFirstItem: 'app-site-item:nth-child(1) .custom-icon-button',
    confirmDialogProceedButton: '.modal-content  .btn-primary',
    confirmDialogCancelButton: '.modal-content  .btn-light'
  },

  login: {
    userName: '#username',
    password: '#password',
    button: '.btn',
    toast: '#loginToast',
    toastMessage: '#loginToast .alert-message span',
    loginToast: '#loginToast'
  },

  sites: {
    cardViewSiteTitle: '.card-body .site-title',
    listTable: '.animation-container',
    imageUploader: 'input#logo_url',
    titleField: '#title',
    domainField: '#domain',
    primaryColor: '#primary_color',
    secondaryColor: '#secondary_color',
    siteTextEditor: '.site-text-editor',
    siteAdvanceCreateButton: '.modal-footer >button:nth-child(3)',
    logoErrorToolTip: 'div.row:nth-child(1) .nico-tooltip',
    titleErrorToolTip: '.nico-tooltip-title',
    domainErrorToolTip: 'div.row:nth-child(3) .nico-tooltip',
    uploadedImageThumbnail: 'img.ng-star-inserted',
    primaryColorPicker: 'div.row:nth-child(4) div:nth-child(7).hex-text input',
    primaryColorPickerOkButton: 'div.row:nth-child(4) button.cp-ok-button-class',
    secondaryColorPicker: 'div.row:nth-child(5) div:nth-child(7).hex-text input',
    secondaryColorPickerOkButton: 'div.row:nth-child(5) button.cp-ok-button-class',
    titleOfFirstSiteListView: '.text-truncate',
    titleOfFirstSiteCardView: '.site-title >h5',
    siteDetailViewSigleSite: '.card-footer .fa-arrow-right',
    messageInSitePreview: '.brand-message',
    siteSettings: 'accordion.panel-group:nth-child(16)',
    instanceFeatureSetting: '.flex-table-td:nth-child(1)',
    settingUpdateModal: '.modal-content',
    enableDisableToggle: '.switch-toggle',
    modalSaveButton: '.modal-content .btn-primary',
    modalCancelButton: '.modal-content .btn-light'
  },

  resellers: {
    imageUploader: 'input#logo_url',
    title: '#title',
    primaryColor: '#primary_color',
    secondaryColor: '#secondary_color',
    description: '#description',
    primaryColorPicker: 'div.row:nth-child(3) div:nth-child(7).hex-text input',
    secondaryColorPicker: 'div.row:nth-child(4) div:nth-child(7).hex-text input',
    primaryColorPickerOkButton: 'div.row:nth-child(3) button.cp-ok-button-class',
    secondaryColorPickerOkButton: 'div.row:nth-child(4) button.cp-ok-button-class',
    logoErrorToolTip: 'div.row:nth-child(1) .nico-tooltip',
    titleErrorToolTip: '.nico-tooltip-title',
    domainErrorToolTip: 'div.row:nth-child(3) .nico-tooltip',
    uploadedImageThumbnail: 'img.ng-star-inserted',
    titleOfFirstResellerCardView: '.site-title >h5',
    singleResellerCardView: '.block-list-view>app-site-item',
    publishUnpublish: '.dropdown li:nth-child(1) > a:nth-child(1)',
    edit: '.dropdown li:nth-child(2) > a:nth-child(1)',
    remove: '.dropdown li:nth-child(3) > a:nth-child(1)'
  },

  videos: {
    cardViewVideoTitle: 'h5.title',
    listTable: '.animation-container',
    titleOfFirstVideoCardView: 'h5.title',
    addVideoSection: '.card.upload-video-section',
    addVideoHeader: '.card.upload-video-section>h5',
    videoLibraryHeader: '#video-library-container h5',
    videoLibrarySection: '#video-library-container',
    videoLibraryList: '.video-library-video-list',
    videoLibraryItemTitle: '.video-library-video-list strong',
    titleInput: '#title',
    descriptionInput: '#description',
    statusSelect: '#status',
    videoUrlInput: '#video_url',
    thumbnailInput: '#addVideoForm .custom-file-uploader input',
    thumbnailUploadButton: 'label.btn:nth-child(2)',
    videoUploadLinkButton: '.link',
    vidoeUrlInputformLink: '.btn-dark',
    videoUploadformlink: '.show-url-input-block:nth-child(1)',
    addGlobalToggle: '.slider',
    videoErrorToolTip: '.nico-tooltip-video-error-tooltip',
    titleErrorToolTip: '.nico-tooltip-title',
    thumbnailErrorToolTip: 'app-upload-thumbnail-image .nico-tooltip',
    thumbnailTitlePlaceHolder: '.custom-file-label',
    cropThumbnailModal: '.modal-content',
    cropThumbnailModalTitle: '.modal-header >h4',
    cropThumbnailModalDoneButton: '.modal-footer >button:nth-child(1)',
    cropThumbnailModalCancelButton: '.modal-footer >button:nth-child(2)',
    cropThumbnailModalKeepOriginalButton: '.modal-footer >button:nth-child(3)',
    previewContainerImage: '.image-preview-container img',
    cropContainerImage: '.crop-container image-cropper img',
  },

  aflac2024theme: {
    feedBackRatingModal: '.feedback-modal-container',
    excellentRating: '.experience-options div:nth-child(1)',
    helpfulRating: '.experience-options div:nth-child(2)',
    okayRating: '.experience-options div:nth-child(3)',
    CouldbeBetterRating: '.experience-options div:nth-child(1)',
    notUsefulRating: '.experience-options div:nth-child(5)',
    notNowButton: '.feedback-modal-container .btn',
    skipButton: '.feedback-modal-container .btn-outline-primary',
    submitButton: '.feedback-modal-container .btn-primary',
    likeButtonFirstItem: '.resource-options >div:nth-child(1) .like-btn',
    dislikeButtonFirstItem: '.resource-options >div:nth-child(1) .dislike-btn',
    likeButtonSecondItem: '.resource-options >div:nth-child(2) .like-btn',
    dislikeButtonSecondItem: '.resource-options >div:nth-child(2) .dislike-btn',
    likeButtonThirdItem: '.resource-options >div:nth-child(3) .like-btn',
    dislikeButtonThirdItem: '.resource-options >div:nth-child(3) .dislike-btn',
    firstCategory: '.aflac-category-list-container>a:nth-child(1)',
    secondCategory: '.aflac-category-list-container>a:nth-child(2)',
    thirdCategory: '.aflac-category-list-container>a:nth-child(3)'
  },

  siteInstance: {
    instanceNav: '.site-side-nav a>span:nth-child(2)',
  }
};

module.exports = { selectors };
