await page.getByRole('button', { name: ' New instance' }).click();
await expect(page.getByRole('heading', { name: ' Create new instance' })).toBeVisible();
await expect(page.getByText('Select a theme')).toBeVisible();
await expect(page.getByText('Homepage & page videos')).toBeVisible();
await expect(page.getByText('Page-specific videos')).toBeVisible();
await expect(page.getByText('Single global video playlist')).toBeVisible();
await expect(page.getByRole('heading', { name: ' Create new instance' })).toBeVisible();
await expect(page.locator('#site-instance-create-edit-form').getByText('Title')).toBeVisible();
await expect(page.getByText('Slug', { exact: true })).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Title' })).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Slug' })).toBeVisible();
await expect(page.locator('#site-instance-create-edit-form')).toContainText('Note: The slug powers all analytics tracking for this instance. Once set, it should not be changed without coordinating with your analytics team - editing it will break historical reporting.');
await expect(page.getByText('Instance URL:http://localhost')).toBeVisible();
await expect(page.getByText('Primary color')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Primary color' })).toBeVisible();
await expect(page.getByText('Secondary color')).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Secondary color' })).toBeVisible();
await expect(page.getByText('Cancel Create')).toBeVisible();
await expect(page.locator('div').filter({ hasText: 'Lyb tile plus' }).nth(5)).toBeVisible();
await page.getByRole('textbox', { name: 'Title' }).click();
await page.getByRole('textbox', { name: 'Title' }).fill('title');
await page.getByText('Slug', { exact: true }).click();
await expect(page.getByRole('textbox', { name: 'Slug' })).toBeVisible();
await page.getByRole('img', { name: 'Lyb tile plus' }).click();
await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
await expect(page.getByRole('button', { name: 'Close' })).toBeVisible();
await page.getByRole('button', { name: 'Close' }).click();