await page.getByText('Phoenix', { exact: true }).click();
await page.getByRole('button', { name: ' New instance' }).click();
await page.getByRole('textbox', { name: 'Title' }).click();
await page.getByRole('textbox', { name: 'Title' }).fill('Min slug validation');
await page.getByRole('textbox', { name: 'Slug' }).click();
await page.getByRole('textbox', { name: 'Slug' }).dblclick();
await page.getByRole('textbox', { name: 'Slug' }).click();
await page.getByRole('textbox', { name: 'Slug' }).click();
await page.getByRole('textbox', { name: 'Slug' }).fill('c');
await page.getByRole('textbox', { name: 'Slug' }).click();
await page.getByRole('button', { name: 'Create' }).click();
await page.getByRole('button', { name: 'Create' }).click();
await page.getByText('Ranjan KarkiSite instances').click();
await page.locator('button').nth(4).click();
await page.getByText('Delete').click();
await page.getByRole('button', { name: 'Proceed' }).click();
await page.goto('http://localhost:4200/manage/sites/3/instances?page=1');